### ISSUE TITLE
I suggest you to tell what version of VS and C# compiler do you used

### ISSUE THREAD

**Issue by RuVT** [trentsartain/Neural-Network#2]
Friendly hello.
I think your project is a good start to who don't know all the thing in Neural Networks but want to know more and practice , we all appreciate that.

I began to check out your code and notice that you are using the new C# 6.0 syntax, that syntax just work for the VS2015 compiler.

So I think that it will be good to tell that in the REDME file, so people dont have problems when compiling.

**Comment by trentsartain** [comment]
Ah, good call.  I thought I had done that, but you are correct.  I'll update the ReadMe.
