### ISSUE TITLE
Saving trained network to the file

### ISSUE THREAD

**Issue by bamsazizi** [trentsartain/Neural-Network#3]
Hi there,

Great job! I couldn't find any method that helps to write/read the trained network to/from the file.
That would be a great option to have because normally training might take few hours and you might not want to do that everytime you start over.

Thanks

**Comment by trentsartain** [comment]
Good timing!  I'm almost finished writing a piece that will allow you to export and import trained networks.  I should have it pushed up sometime this week.

**Comment by NeoxzAI** [comment]
Hi trentsartain, amazing work. You finished the write/read for trained networks?

**Comment by NeoxzAI** [comment]
I tried to serialize but didn't work, the data loading saved networks got corrupted, so can you help me please?

**Comment by trentsartain** [comment]
Hey, sorry, I ended up having a really busy year of work, but things are calming down so I'll try to finish up the code to help with importing/exporting of networks.

**Comment by NeoxzAI** [comment]
Thank you!

**Comment by trentsartain** [comment]
Hello!  I just committed some pretty big changes.  Among them is the ability to import and export fully trained networks and datasets.  Let me know what you think.  README is updated too.
