### ISSUE TITLE
Standardise on spacing

### ISSUE THREAD

**Issue by ashleybroughton** [trentsartain/Neural-Network#4]
There seems to be a horrible mix of tabs and spaces in use.
Recommend standardising on one type (usually spaces).

Automatic conversion of tabs to spaces or vice versa can be set in the Visual Studio editor settings.

https://github.com/trentsartain/Neural-Network/blob/61566e2676698fb73eea0e92e36e30a12cd7e4d5/NeuralNetwork/NeuralNetwork/Program.cs

**Comment by trentsartain** [comment]
Good catch.  I had that set up on one of my machines, but not the other, so it looks like it started mixing.  I hadn't looked at the files in Github before, so I didn't even notice! 

All fixed now. Thanks!
